### PR TITLE
Update archiver, tumbnailer, rpc commands

### PR DESCRIPTION
**Pull request by kris-lab**
Depends on https://github.com/cargomedia/CM/pull/1665

Follow up steps:
- [ ] update puppet packages

### CODE REVIEW

**Comment by kris-lab** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Looks good.

**Comment by kris-lab** [comment]
Good! so let's test it and release as `0.1.2`

**Comment by kris-lab** [comment]
@njam do you see any downside to compile, tag and release it as `0.1.2`?

**Comment by njam** [comment]
We have a version constraint in [puppet-packages](https://github.com/cargomedia/puppet-packages/blob/master/modules/wowza/manifests/jar/cm_wowza.pp#L1), so should be fine!

**Pull request merged**
